name: CI/CD to EC2

on:
  push:
    branches: ["test"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t kevinseya/logistic_update_user:latest .

      - name: Push Docker Image
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push kevinseya/logistic_update_user:latest

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for EC2 access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            # Verificar e instalar Docker si es necesario.
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Download the image
            sudo docker pull kevinseya/logistic_update_user:latest

            # Stop and remove previous container
            sudo docker stop logistic_update_user || true
            sudo docker rm logistic_update_user || true

            # Generate .env file
            echo "DB_IP=${{ secrets.DB_IP }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "URL_WEBSOCKET=${{ secrets.URL_WEBSOCKET }}" >> .env

            # Run new container
            sudo docker run -d --name logistic_update_user \
              --env-file .env \
              -p 8082:8082 \
              kevinseya/logistic_update_user:latest
          EOF
